### ISSUE TITLE
Error white creating  single table

### ISSUE THREAD

**Issue by jaydeepakbari** [Hiren86/AutoCRUD#1]
SQLSTATE[HY000]: General error: 1364 Field 'layout' doesn't have a default value (SQL: insert into `page_layouts` (`table`, `updated_at`, `created_at`) values (customer, 2018-04-02 13:34:26, 2018-04-02 13:34:26))

**Comment by Hiren86** [comment]
Kindly, read the documentation at http://autocrud.accurateweb.in already mention in documentation under **other error** section

**Comment by jaydeepakbari** [comment]
Thanks
