### ISSUE TITLE
Error on generate View

### ISSUE THREAD

**Issue by num3r06** [Hiren86/AutoCRUD#2]
Hi,
Very good job.
I've a problem: on generate single table form, the field's order is different from label order in table and in the form. So in the column first name i've cell number and so on

**Comment by Hiren86** [comment]
Hi Salvatore,
Thanks for your suggestion, currently you can't sort the fields with a single table. but, I will implement it soon.

**Comment by num3r06** [comment]
Forgive me for misunderstanding. I wanted to say that in the table view the column headers do not match the content. for example under the column last name there is address

**Comment by Hiren86** [comment]
Thanks for explain me your problem, I got your problem now but i want to know that how you generate view for it so can you please make a doc file and send me on hirenmangukiya86@gmail.com.
